#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# event nethserver-sssd-update event
#
event_templates('nethserver-sssd-update', qw(
    /etc/openldap/ldap.conf
));

event_actions('nethserver-sssd-update', qw(
    initialize-default-databases   00
));

#
# event nethserver-sssd-save
#
event_templates('nethserver-sssd-save', qw(
    /etc/sssd/sssd.conf
    /etc/samba/smb.conf
    /etc/openldap/ldap.conf
));
event_actions('nethserver-sssd-save', qw(
    nethserver-sssd-conf    20
    nethserver-sssd-initkeytabs 30
    nethserver-sssd-notifyclients 80
));
event_services('nethserver-sssd-save', qw(
    sssd restart
));

validator_actions('ad-dns', qw(
   srv_record 20
));

# actions for user-create validator
validator_actions('user-create', qw(
                  user-length 30
));

# actions for user-delete validator
validator_actions('user-delete', qw(
    account-removable 20
));

# actions for group-create validator
validator_actions('group-create', qw(
                  group-length 30
));

# actions for group-delete validator
validator_actions('group-delete', qw(
    account-removable 20
));

#------------------------------------------------------
# Clear SSSD cache at the end of all user/group events
#------------------------------------------------------

event_actions($_, qw(
    nethserver-sssd-clear-cache     90
)) foreach(qw(
    user-create
    user-modify
    user-delete
    user-lock
    user-unlock
    group-create
    group-modify
    group-delete
));

#--------------------------------------------------------
# Clear SSSD before password-policy-update extra actions
#--------------------------------------------------------

event_actions('password-policy-update', qw(
    nethserver-sssd-clear-cache 10
));

# actions for myhostname validator
validator_actions('myhostname', qw(
    failifjoin 00
));
