#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-sssd-update event
#--------------------------------------------------

my $event = "nethserver-sssd-update";

event_actions('nethserver-sssd-update', qw(
              initialize-default-databases   00
              nethserver-sssd-conf           20
));
event_services($event, 'sssd' => 'restart');
templates2events("/etc/sssd/sssd.conf",  $event);

# actions for user-create validator
validator_actions('user-create', qw(
                  uniq-account 20
                  user-length 30
                  max-users 90
));

# actions for user-delete validator
validator_actions('user-delete', qw(
    account-removable 20
));

# actions for group-create validator
validator_actions('group-create', qw(
                  uniq-account 20
                  group-length 30
                  reserved-group 40
));

# actions for group-delete validator
validator_actions('group-delete', qw(
    account-removable 20
));

#--------------------------------------------------
# password-expired event
#--------------------------------------------------
event_actions('password-expired', qw(
    nethserver-sssd-mail-password-expired 40
));

# Add warnpassexpire script in cron.daily jobs list -- Refs #1073
safe_symlink('/sbin/e-smith/warnpassexpire', 'root/etc/cron.daily/warnpassexpire');

