#!/usr/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

workgroup=$(testparm -s -d 0 --parameter-name=workgroup 2>/dev/null)
systemname=$(hostname -s)
netbiosname=${systemname:0:15}\$

echo "NetBIOS domain name: $workgroup"

exec timeout --signal=HUP --kill-after=10 10 /usr/bin/bash -s <<EOF
net ads info
echo ""
krb5exec klist -s && echo -e "Join is OK\n"
krb5exec net ads search -k "(&(sAMAccountName=${netbiosname})(objectCategory=computer))" \
        name \
        sAMAccountName \
        distinguishedName \
        servicePrincipalName \
        objectSid \
        dNSHostName \
        pwdLastSet \
        lastLogon \
        whenCreated \
        whenChanged \
        accountExpires \
    | tail -n +3
EOF
