#!/usr/bin/perl -w

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::AccountsDB;
use JSON;

my %accountsDb = esmith::AccountsDB->as_hash() or die "Couldn't open AccountsDB\n";
my %users;

open(SPH, '/usr/bin/getent shadow |') || die;

while(my $shadowEntry = <SPH>) {
    chomp($shadowEntry);

    # see shadow.h
    my ($namp, $pwdp, $lstchgm, $min, $max, $warn, $inact, $expire) = split(':', $shadowEntry);

    # skip non-user entries and non-active users:
    if( ! defined $accountsDb{$namp} 
	|| $accountsDb{$namp}{'type'} ne 'user'
	|| $accountsDb{$namp}{'__state'} ne 'active'
	) {
	next;
    }

    my $today = time;
    my $expiration = ($lstchgm + $max) * 86400;
    $users{$namp} = 0;
    
    if ($expiration < time) {
        $users{$namp} = 1;
    }
    
}

close(SPH);

print to_json(\%users);

exit(0);

