#!/usr/bin/perl

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use JSON;
use NethServer::SSSD;

my $o = NethServer::SSSD->new();

my $dump = {
    'BaseDN' => $o->baseDN(),
    'BindDN' => $o->bindDN(),
    'BindPassword' => $o->bindPassword(),
    'UserDN' => $o->userDN(),
    'GroupDN' => $o->groupDN(),
    'LdapURI' => $o->ldapURI(),
    'host' => $o->host(),
    'port' => $o->port(),
    'startTls'=> $o->startTls()
};

my $cmd = shift;

if($cmd eq 'dump') {
    print JSON::to_json($dump, {utf8 => 1, pretty => 1});
    exit(0);
}

if( ! -x '/usr/bin/ldapsearch') {
    warn "[ERROR] cannot execute /usr/bin/ldapsearch. To workaround this type:\n\n     yum install openldap-clients\n";
    exit(1);
}

exec('/usr/bin/ldapsearch', ($o->startTls() ? '-ZZ' : ()), '-s', 'base', '-x', '-H', $dump->{'LdapURI'}, '-D', $dump->{'BindDN'}, '-w', $dump->{'BindPassword'}, '-b', $dump->{'BaseDN'}, '(objectClass=*)');

