#!/usr/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Supported ns6 upgrade paths:
# - WS/PDC to local AD,
# - ADS to remote AD,
# - NONE/WS to local LDAP
#
# Methods:
# - restore from ns6 backup
# - rsync-upgrade
#

event=$1
ns6upgrade_flag=/var/run/.nethserver-upgrade-configdb

if [[ "${event}" == "nethserver-directory-ns6upgrade" ]]; then
    if [[ -f ${ns6upgrade_flag} ]]; then
        # We will run lately, in post-restore-data event
        exit 0
    fi
elif [[ ! -f ${ns6upgrade_flag} ]]; then
    # No flag set, nothing to do
    exit 0
fi

provider=$(/sbin/e-smith/config getprop sssd Provider)

if [[ ${provider} == "ad" ]]; then
    primary_group='domain users'
elif [[ ${provider} == "ldap" ]]; then
    primary_group='locals'
else
    exit 0
fi

if ! getent group "${primary_group}"; then
    echo "[ERROR] could not find ${primary_group} group" 1>&2
    exit 1
fi

echo "[NOTICE] Upgrading home directories permissions for ${provider^^} account provider"
shopt -s nullglob
for D in /var/lib/nethserver/home/*; do
    chown -R "$(basename "${D}")":"${primary_group}" "$D" || ((++errors));
done

if (( errors > 0 )); then
    echo "[ERROR] Failed to chown permissions on home directories" 1>&2
    exit 1
fi

exit 0
