#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

if [ -f /var/lib/nethserver/backup/secrets_tdb.dump ]; then
   if [ -f /var/lib/samba/private/secrets.tdb ]; then # backup old tdb
       mv /var/lib/samba/private/secrets.tdb /var/lib/samba/private/secrets.tdb.bak
   fi
   /usr/bin/tdbrestore /var/lib/samba/private/secrets.tdb < /var/lib/nethserver/backup/secrets_tdb.dump
   chmod 600 /var/lib/samba/private/secrets.tdb
fi
