#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

flag_path=/var/cache/nethserver-adcredsrequired

#
# Find NethServer::SSSD Perl module usages in actions and templates then
# print the list of update events of dependant packages.
#

module_usages=$(grep -l -R -F NethServer::SSSD /etc/e-smith/events/actions/ /etc/e-smith/templates/ \
    | xargs -- rpm -qf --queryformat '%{NAME}\n' \
    | grep -v -E 'nethserver-(dc|sssd|directory)' | sort | uniq)

event_watchers=$(find /etc/e-smith/events/nethserver-sssd-save/ -type f -o -type l | xargs -- rpm -qf --queryformat '%{NAME}\n' \
    | grep -v -E 'nethserver-(dc|sssd|directory)' | sort | uniq)

# Credentials are optional if no package subscribed nethserver-sssd-save event 
# or requires NethServer::SSSD
if [[ -z "$module_usages" && -z "$event_watchers" ]]; then
    rm -f ${flag_path}
else
    touch ${flag_path}
fi


