#!/bin/bash

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

event=$1
sourceDir=$2

workgroup=$(/sbin/e-smith/db ${sourceDir}/home/e-smith/db/configuration getprop smb Workgroup | tr '[:lower:]' '[:upper:]')
serverRole=$(/sbin/e-smith/db ${sourceDir}/home/e-smith/db/configuration getprop smb ServerRole)

if [[ -n "${workgroup}" && "${serverRole}" == "PDC" ]]; then
    echo "[NOTICE] Forcibly migrate the PDC workgroup name ${workgroup}"
    /sbin/e-smith/config setprop sssd Workgroup "${workgroup}"
else
    echo "[NOTICE] ServerRole is ${serverRole}, workgroup name not migrated"
fi
