#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Signal *-update events on packages that include NethServer::SSSD library
# Exclude nethserver-sssd itself and local accounts providers.

ERRORS=0

tmp_patterns=$(mktemp)
trap 'rm -f ${tmp_patterns}' EXIT

# Prepare the list of excluded events:
find /etc/e-smith/events/nethserver-sssd-save/ -type f -o -type l | xargs -- rpm -qf --queryformat '%{NAME}-update\n' \
    | sort | uniq >$tmp_patterns

for SUBEVENT in $(grep -l -R -F NethServer::SSSD /etc/e-smith/events/actions/ /etc/e-smith/templates/ \
    | xargs -- rpm -qf --queryformat '%{NAME}-update\n' \
    | grep -v -E 'nethserver-(dc|sssd|directory)-update' \
    | grep -v -F -f ${tmp_patterns} | sort | uniq ); do
    echo "[WARNING] DEPRECATED! Package ${SUBEVENT%-update} must subscribe nethserver-sssd-save event explicitly"
    /sbin/e-smith/signal-event $SUBEVENT || (( ERRORS ++ ))
done

if (( ERRORS > 0 )); then
    exit 1
fi
