#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

use esmith::event;

my $file = shift;
my $separator = shift;

if($file) {
    open(FH, "<", $file) or die;
} else {
    open(FH, "-");
}

if( ! $separator) {
    $separator = "\t";
}

while(<FH>) {

    # Remove trailing whitespace:
    chomp $_;
    $_ =~ s/\s+$//;

    my @parts = split(/$separator/, $_);
    my $groupname = $parts[0];

    if( ! $groupname) {
        next;
    }

    if( ! esmith::event::event_signal('group-create', @parts) ) {
        warn "[ERROR] Account `$groupname` group-create event failed.\n";
        next;
    }

    shift @parts;
    warn "[INFO] imported '$groupname' with members '".join(' ', @parts)."'\n";

}

