#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use esmith::ConfigDB;
use esmith::AccountsDB;

my $db = esmith::ConfigDB->open_ro() or exit 1;
my $accountdb = esmith::AccountsDB->open_ro() or exit 1;


=head2 checkMaxUsers()

Returns an error message if the current number of users is greater than or
equal to the sysconfig|MaxUsers property.

Takes the name of the next page to go to if the test succeeds as an argument.

=cut

# Get value of MaxUsers if it exists.
my $sysconfig = $db->get('sysconfig');
my $maxUsers = (($sysconfig) ? $sysconfig->prop('MaxUsers') : '') || '';
my $activeUsers = scalar $accountdb->activeUsers() || 0;
if ((defined $activeUsers && $maxUsers ne '')
    && ($activeUsers >= $maxUsers))
{
    print "Max users: $maxUsers\n";
    exit 1;
}

exit 0;


