#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

package esmith;

use esmith::AccountsDB;


=head2 validate_acctName_conflict

Returns 'OK' if the account name doesn't yet exist.  Returns a localised error
otherwise.

=cut

my $acctName = shift || die('Missing account name argument');
my $accountdb = esmith::AccountsDB->open_ro() || die('Could not open AccountsDB');

my $account = $accountdb->get($acctName);
my $type;

if (defined $account)
{
    $type = $account->prop('type');
}
elsif (defined getpwnam($acctName) || defined getgrnam($acctName))
{
    $type = "system";
}
else
{
    exit 0;
}

print "A $type account with the same name already exists\n";
exit 3;
